/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banque;

/**
 *
 * @author ldivi
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichiers = new javax.swing.JMenu();
        clients = new javax.swing.JMenuItem();
        comptes = new javax.swing.JMenuItem();
        transaction = new javax.swing.JMenu();
        depot = new javax.swing.JMenuItem();
        retrait = new javax.swing.JMenuItem();
        transfert = new javax.swing.JMenu();
        compteTo = new javax.swing.JMenuItem();
        rapport = new javax.swing.JMenu();
        rapportClient = new javax.swing.JMenuItem();
        solde = new javax.swing.JMenu();
        checkSolde = new javax.swing.JMenuItem();
        grandCompte = new javax.swing.JMenu();
        userCompte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        fichiers.setText("Enrégistrements et création de comptes");
        fichiers.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        clients.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        clients.setText("Clients");
        clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsActionPerformed(evt);
            }
        });
        fichiers.add(clients);

        comptes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        comptes.setText("Comptes");
        comptes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comptesActionPerformed(evt);
            }
        });
        fichiers.add(comptes);

        jMenuBar1.add(fichiers);

        transaction.setText("Transaction");
        transaction.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        depot.setText("Dépôt");
        depot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depotActionPerformed(evt);
            }
        });
        transaction.add(depot);

        retrait.setText("Retrait");
        retrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retraitActionPerformed(evt);
            }
        });
        transaction.add(retrait);

        jMenuBar1.add(transaction);

        transfert.setText("Transfert");
        transfert.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        compteTo.setText("Compte vers Compte");
        compteTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compteToActionPerformed(evt);
            }
        });
        transfert.add(compteTo);

        jMenuBar1.add(transfert);

        rapport.setText("Rapport");
        rapport.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        rapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapportActionPerformed(evt);
            }
        });

        rapportClient.setText("Rapport des eregistrements");
        rapportClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapportClientActionPerformed(evt);
            }
        });
        rapport.add(rapportClient);

        jMenuBar1.add(rapport);

        solde.setText("Solde");
        solde.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldeActionPerformed(evt);
            }
        });

        checkSolde.setText("Vérification du solde");
        checkSolde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSoldeActionPerformed(evt);
            }
        });
        solde.add(checkSolde);

        jMenuBar1.add(solde);

        grandCompte.setText("Gestionnaires");
        grandCompte.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        userCompte.setText("Gestionnaire de compte");
        userCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCompteActionPerformed(evt);
            }
        });
        grandCompte.add(userCompte);

        jMenuBar1.add(grandCompte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comptesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comptesActionPerformed
        // TODO add your handling code here:
        
        Compte cp = new Compte();
        jDesktopPane1.add(cp);
        cp.setVisible(true);
    }//GEN-LAST:event_comptesActionPerformed

    private void clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsActionPerformed
        // TODO add your handling code here:
        
        Clients cl = new Clients();
        jDesktopPane1.add(cl);
        cl.setVisible(true);
        
    }//GEN-LAST:event_clientsActionPerformed

    private void depotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depotActionPerformed
        // TODO add your handling code here:
        
        Depot dp = new Depot();
        jDesktopPane1.add(dp);
        dp.setVisible(true);
    }//GEN-LAST:event_depotActionPerformed

    private void retraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retraitActionPerformed
        // TODO add your handling code here:
        
        Retrait rt = new Retrait();
        jDesktopPane1.add(rt);
        rt.setVisible(true);
    }//GEN-LAST:event_retraitActionPerformed

    private void compteToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compteToActionPerformed
        // TODO add your handling code here:
        
        Transfert tf = new Transfert();
        jDesktopPane1.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_compteToActionPerformed

    private void rapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rapportActionPerformed

    private void soldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldeActionPerformed

    private void rapportClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapportClientActionPerformed
        // TODO add your handling code here:
        Rapport rpt = new Rapport();
        jDesktopPane1.add(rpt);
        rpt.setVisible(true);
    }//GEN-LAST:event_rapportClientActionPerformed

    private void checkSoldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSoldeActionPerformed
        // TODO add your handling code here:
        
        Solde sd = new Solde();
        jDesktopPane1.add(sd);
        sd.setVisible(true);  
        
    }//GEN-LAST:event_checkSoldeActionPerformed

    private void userCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCompteActionPerformed
        // TODO add your handling code here:
        
        Gestionnaire gs = new Gestionnaire();
        jDesktopPane1.add(gs);
        gs.setVisible(true);
        
    }//GEN-LAST:event_userCompteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem checkSolde;
    private javax.swing.JMenuItem clients;
    private javax.swing.JMenuItem compteTo;
    private javax.swing.JMenuItem comptes;
    private javax.swing.JMenuItem depot;
    private javax.swing.JMenu fichiers;
    private javax.swing.JMenu grandCompte;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu rapport;
    private javax.swing.JMenuItem rapportClient;
    private javax.swing.JMenuItem retrait;
    private javax.swing.JMenu solde;
    private javax.swing.JMenu transaction;
    private javax.swing.JMenu transfert;
    private javax.swing.JMenuItem userCompte;
    // End of variables declaration//GEN-END:variables
}
